### ISSUE TITLE
add label for policy attachment to CRDs

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/multicluster-gateway-controller#517] opened 2023-09-12 12:39 UTC
As stated in the Gateway API [spec](https://gateway-api.sigs.k8s.io/geps/gep-713/#standard-label-on-crd-objects), each CRD that defines a policy object MUST include the standard label `gateway.networking.k8s.io/policy: inherited|direct`.

**Comment by guicassolato** [comment] 2023-09-12 12:41
Duplicate of #463

**Closed by guicassolato** 2023-09-12 12:41 UTC
